config/routes.rb
Rails.application.routes.draw do
  devise_for :autors
  get 'articulos/new'

  get 'articulos/index'

  get 'articulos/show'

  get 'estaticas/home'

  get 'estaticas/index'

  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '*path' => redirect("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  belongs_to :autor, optional: true
  has_many :comentarios, dependent: :destroy

  validates :titulo, presence: {:message => "no vacio"}
  validates :contenido, presence: {:message => "no vacio"}
  lenghth: {minimum: 50, message => "minimo 50"}
end

app/models/autor.rb
class Autor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  def new
    @boton = "Crear"
    #@articulo= Articulo.new
    @articulo= current_autor.articulos.build
  end

  def index
  end

  def create
      #@articluo= Articulo.new(articulo_params)
      @articluo= current_autor.articulos.build(articulo_params)
      if @articulo.save
        redirect_to @articulo
      else
        render 'new'
      end

  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

  private
  def articulo_params
    params.require(:articulo).permit(:titulo, :contenido)
  end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def home
  end

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articulos/index.html.erb
<h1>Articulos#index</h1>
<p>Find me in app/views/articulos/index.html.erb</p>

app/views/articulos/new.html.erb
<h1>Articulos#new</h1>
<p>Find me in app/views/articulos/new.html.erb</p>

<% form_for @articulo do |f| %>

    <% if @articulo.error.any? %>
        <div id="errors">
            <ul>
                <% @articulo.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <%= f.label :titulo %>
    <%= f.html_field :titulo %>
    <%= f.label :contenido %>
    <%= f.html_area :contenido %>
    <%= f.bottom "Crear articulo" %>

<% end %>

app/views/articulos/show.html.erb
<h1>Articulos#show</h1>
<p>Find me in app/views/articulos/show.html.erb</p>

app/views/estaticas/home.html.erb
<h1>Estaticas#home</h1>
<p>Find me in app/views/estaticas/home.html.erb</p>

app/views/estaticas/index.html.erb
<h1>Estaticas#index</h1>
<p>Find me in app/views/estaticas/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= link_to 'home', root_path %>
  
  <%= link_to 'iniciar sesión', new_autor_session_path %>
  <%= link_to 'crear cuenta', new_autor_registration_path %>
  <%= link_to 'cerrar sesión', destroy_autor_session_path, method: :delete %>
  <%= link_to 'editar', edit_autor_registration_path %>

    <%= yield %>
  </body>
</html>